'use client';

import {useCallback,useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Check,Clapperboard,Film,Star} from 'lucide-react';
import {toast,Toaster} from 'sonner';
import type {Title} from '@/lib/watchlist';

type Response={titles?:Title[];error?:string;connected?:boolean};

export default function WatchedPage(){
 const [titles,setTitles]=useState<Title[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [editing,setEditing]=useState<Title|null>(null);const [review,setReview]=useState('');const [rating,setRating]=useState('');const [watchedOn,setWatchedOn]=useState('');const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/watchlist',{cache:'no-store'});const j=await r.json() as Response;if(!r.ok)throw new Error(j.error||'Could not load watched titles.');setTitles((j.titles||[]).filter(t=>t.status==='Watched'));setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load watched titles.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const reviewed=useMemo(()=>titles.filter(t=>t.review||t.rating).length,[titles]);
 function openReview(title:Title){setEditing(title);setReview(title.review||'');setRating(title.rating||'');setWatchedOn(title.watchedOn||'')}
 async function saveReview(e:React.FormEvent){e.preventDefault();if(!editing)return;setSaving(true);try{const r=await fetch('/api/watchlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'edit',id:editing.id,review,rating,watchedOn})});const j=await r.json() as Response;if(!r.ok)throw new Error(j.error||'Could not save your review.');toast.success('Review saved');setEditing(null);await load()}catch(e){toast.error(e instanceof Error?e.message:'Could not save your review.')}finally{setSaving(false)}}
 return <><Toaster theme="dark" richColors/><header className="topbar"><a className="brand" href="/"><Clapperboard size={23}/><span>Show List<span className="brand-dot">.</span></span></a><span className="private-label">Your watched shelf</span><a className="sheet-link" href="/">Back to watchlist <ArrowLeft size={16}/></a></header><main className="watched-page"><div className="intro"><div><h1>Watched, remembered.</h1><p>{reviewed?`${reviewed} of ${titles.length} watched titles have a rating or review.`:'Add a quick thought while it is still fresh.'}</p></div></div>{loading?<p className="quiet">Loading your watched titles…</p>:error?<div className="empty"><Film size={28}/><h2>Could not load your watched shelf</h2><p>{error}</p><button className="secondary" onClick={()=>void load()}>Try again</button></div>:!titles.length?<div className="empty"><Check size={28}/><h2>Nothing marked watched yet</h2><p>When you finish something, mark it Watched from its details and it will appear here.</p><a className="primary" href="/">Browse watchlist</a></div>:<section className="watched-list" aria-label="Watched titles">{titles.map(title=><article className="watched-row" key={title.id}><div className="watched-poster">{title.poster?<img src={title.poster} alt=""/>:<Film size={22}/>}</div><div className="watched-copy"><p className="title-meta">{title.type||'Title'}{title.year?` · ${title.year}`:''}</p><h2>{title.title}</h2>{title.rating&&<p className="review-rating"><Star size={14} fill="currentColor"/> {title.rating}/5</p>}{title.review?<p className="review-excerpt">{title.review}</p>:<p className="quiet">No review yet.</p>}</div><button className="secondary review-action" onClick={()=>openReview(title)}>{title.review||title.rating?'Edit review':'Add review'}</button></article>)}</section>} {editing&&<div className="review-overlay" role="presentation"><form className="review-form" onSubmit={saveReview}><div><p className="title-meta">Your review</p><h2>{editing.title}</h2></div><label>My rating<select value={rating} onChange={e=>setRating(e.target.value)}><option value="">No rating</option>{['1','2','3','4','5'].map(value=><option key={value} value={value}>{value} / 5</option>)}</select></label><label>Watched on<input type="date" value={watchedOn} onChange={e=>setWatchedOn(e.target.value)}/></label><label>Review<textarea value={review} maxLength={4000} onChange={e=>setReview(e.target.value)} placeholder="What did you think?"/></label><div className="form-actions"><button className="secondary" type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save review'}</button></div></form></div>}</main></>;
}
