'use client';
import {useMemo,useState,useEffect,useCallback} from 'react';
import {Search,Plus,Play,Bookmark,Check,Film,ArrowUpRight,SlidersHorizontal,Library,Clapperboard,Download} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import initialCatalog from '@/data/catalog.json';
import releaseDates from '@/data/release-dates.json';
import {displayDate,localToday,releaseCue,sortByRelease,offlineSources,type Title} from '@/lib/watchlist';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {toast,Toaster} from 'sonner';
export default function Home(){
 const [catalog,setCatalog]=useState<Title[]>((initialCatalog as Title[]).map(r=>({...r,...(releaseDates as Record<string,Partial<Title>>)[r.id]})));const [connected,setConnected]=useState(false);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState('');const [today,setToday]=useState(localToday);
 const [selected,setSelected]=useState<Title|null>(null);const [addOpen,setAddOpen]=useState(false);const [title,setTitle]=useState('');const [hint,setHint]=useState('');const [saving,setSaving]=useState(false);const [saveError,setSaveError]=useState('');const [newId,setNewId]=useState('');const [limit,setLimit]=useState(30);const [connectionOpen,setConnectionOpen]=useState(false);const [searching,setSearching]=useState(false);const [searchError,setSearchError]=useState('');const [searchResults,setSearchResults]=useState<Array<{tmdbId:number;title:string;type:string;year:string;poster:string|null;providers:Array<{provider_name:string;access_type:string}>;available:boolean}>>([]);
 const reload=useCallback(async()=>{setLoading(true);try{const response=await fetch('/api/watchlist');const data=await response.json() as {titles?:Title[];connected?:boolean;error?:string};if(data.titles)setCatalog(data.titles);setConnected(Boolean(data.connected));setLoadError(response.status===401?'Showing your saved sheet. Connect Google Sheets to enable live updates.':data.error||'');}catch{setLoadError('Could not refresh your list. Showing the last saved copy.');}finally{setLoading(false)}},[]);
 useEffect(()=>{void reload()},[reload]);
 useEffect(()=>{const tick=()=>setToday(localToday());const timer=setInterval(tick,60000);return()=>clearInterval(timer)},[]);
 async function save(payload:Record<string,unknown>){setSaving(true);setSaveError('');try{const res=await fetch('/api/watchlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error||'Could not save. Please retry.');await reload();toast.success('Saved to Google Sheets');return true}catch(e){const message=e instanceof Error?e.message:'Could not save. Please retry.';setSaveError(message);toast.error(message);return false}finally{setSaving(false)}}
 async function addTitle(e:React.FormEvent){e.preventDefault();if(await save({action:'add',id:newId,title,serviceHint:hint})){setAddOpen(false);setTitle('');setHint('')}}
 async function changeStatus(status:string){if(selected&&await save({action:'status',id:selected.id,status})){setSelected({...selected,status})}}
 async function searchTitles(value=title){const q=value.trim();if(q.length<2){setSearchError('Enter at least two characters to search.');return}setSearching(true);setSearchError('');try{const r=await fetch(`/api/title-search?q=${encodeURIComponent(q)}`);const data=await r.json() as {titles?:typeof searchResults;error?:string};if(!r.ok)throw new Error(data.error||'Could not search right now.');setSearchResults(data.titles||[])}catch(e){setSearchError(e instanceof Error?e.message:'Could not search right now.')}finally{setSearching(false)}}
 function chooseResult(result:(typeof searchResults)[number]){setTitle(result.title);setHint(result.providers.map(p=>p.provider_name).filter((value,index,all)=>all.indexOf(value)===index).join('; '));setNewId(crypto.randomUUID());setSearchResults([]);setSearchError('');setAddOpen(true)}
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:'start_watchlist_title_entry',title:'Start adding a watchlist title',description:'Open the Add a title form in Show List with a title and optional network or service. This stages an entry; it does not save to Google Sheets.',inputSchema:{type:'object',properties:{title:{type:'string',minLength:1,maxLength:250},networkService:{type:'string',maxLength:150}},required:['title'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const x=input as {title?:unknown;networkService?:unknown};if(!x||typeof x.title!=='string'||!x.title.trim()||x.title.length>250||x.networkService!==undefined&&(typeof x.networkService!=='string'||x.networkService.length>150))throw new Error('Enter a title and an optional network or service.');setNewId(crypto.randomUUID());setTitle(x.title.trim());setHint(typeof x.networkService==='string'?x.networkService:'');setSaveError('');setAddOpen(true);return {staged:true,title:x.title.trim(),savingAvailable:connected}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return()=>lifecycle.abort();
 },[connected]);

 const [query,setQuery]=useState('');const [tab,setTab]=useState('Want to Watch');const [type,setType]=useState('all');const [service,setService]=useState('all');const [availability,setAvailability]=useState('all');
 const services=useMemo(()=>[...new Set(catalog.flatMap(r=>r.providers.map(p=>p.provider_name)))].sort(),[catalog]);
 useEffect(()=>setLimit(30),[catalog,query,tab,type,service,availability]);
 const rows=useMemo(()=>sortByRelease(catalog.filter(r=>(tab==='all'||r.status===tab)&&(!query||r.title.toLowerCase().includes(query.toLowerCase()))&&(type==='all'||r.type===type)&&(service==='all'||r.providers.some(p=>p.provider_name===service))&&(availability==='all'||(availability==='available'?r.availability==='available':availability==='unavailable'?['rent_buy_only','no_data'].includes(r.availability):availability==='offline'?offlineSources(r).length>0:r.matchStatus==='needs_review'))),today),[catalog,query,tab,type,service,availability,today]);
 return <><Toaster theme="dark" richColors/><header className="topbar"><a className="brand" href="/"><Clapperboard size={23}/><span>Show List<span className="brand-dot">.</span></span></a><span className="private-label">Your personal collection</span><a className="sheet-link" href="/watched">Watched <Check size={16}/></a><a className="sheet-link" href="https://docs.google.com/spreadsheets/d/1QHdc7GR5HxY3rJuOvsYe0Bf7b5TZcxXzeW8YuXub5qU/edit" target="_blank" rel="noreferrer">Open sheet <ArrowUpRight size={16}/></a></header>
 <main><div className="intro"><div><h1>A good night starts here.</h1><p>Your list. Your services. Something worth watching.</p></div><button className="primary" onClick={()=>{setNewId(crypto.randomUUID());setSaveError('');setAddOpen(true)}}><Plus size={19}/> Add a title</button></div>
 {(!connected&&!loading||loadError)&&<div className="connection-note"><span>{loadError||'Showing your saved sheet. Connect Google Sheets to enable live updates and editing.'}</span><button onClick={()=>setConnectionOpen(true)}>Connect sheet <ArrowUpRight size={14}/></button></div>}
 <div className="collection-nav"><Tabs value={tab} onValueChange={setTab}><TabsList className="watch-tabs"><TabsTrigger value="Want to Watch"><Bookmark size={16}/>To watch <span>{catalog.filter(r=>r.status==='Want to Watch').length}</span></TabsTrigger><TabsTrigger value="Watching"><Play size={16}/>Watching</TabsTrigger><TabsTrigger value="Watched"><Check size={16}/>Watched</TabsTrigger><TabsTrigger value="all"><Library size={16}/>All titles <span>{catalog.length}</span></TabsTrigger></TabsList></Tabs><span className="region">US availability</span></div>
 <div className="filters"><label className="search"><Search size={19}/><input placeholder="Find a movie or show…" aria-label="Search titles and services" value={query} onChange={e=>{setQuery(e.target.value);setSearchResults([]);setSearchError('')}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void searchTitles(query)}}}/>{searching&&<span className="searching-label">Checking services…</span>}</label><Select value={type} onValueChange={setType}><SelectTrigger className="filter-select"><SelectValue placeholder="Movies & shows"/></SelectTrigger><SelectContent><SelectItem value="all">Movies & shows</SelectItem><SelectItem value="Movie">Movies</SelectItem><SelectItem value="Series">Shows</SelectItem></SelectContent></Select><Select value={service} onValueChange={setService}><SelectTrigger className="filter-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All services</SelectItem>{services.map(s=><SelectItem value={s} key={s}>{s}</SelectItem>)}</SelectContent></Select><Select value={availability} onValueChange={setAvailability}><SelectTrigger className="filter-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Any availability</SelectItem><SelectItem value="available">Streaming now</SelectItem><SelectItem value="offline">iPad download options</SelectItem><SelectItem value="unavailable">No Steam Currently</SelectItem><SelectItem value="review">Needs clarification</SelectItem></SelectContent></Select></div>
 {searchError&&query.length>=2&&<p role="alert" className="form-error main-search-error">{searchError}</p>}{searchResults.length>0&&<div className="main-search-results"><p>Streaming matches · choose one to add it</p><div className="search-results" aria-label="Streaming search results">{searchResults.map(result=><button type="button" className="search-result" key={`${result.type}-${result.tmdbId}`} onClick={()=>chooseResult(result)}>{result.poster?<img src={result.poster} alt=""/>:<Film size={18}/>}<span><strong>{result.title}</strong><small>{result.type}{result.year?` · ${result.year}`:''} · {result.available?result.providers.map(p=>p.provider_name).filter((value,index,all)=>all.indexOf(value)===index).join(', '):'No Stream Currently'}</small></span></button>)}</div></div>}
 <div className="results-line"><p><strong>{rows.length}</strong> titles {availability==='available'?'streaming now':'in your collection'} <span className="sort-explainer">· Upcoming, then recently released</span></p><button className="refresh-list" onClick={()=>void reload()} disabled={loading}>{loading?'Refreshing…':connected?'Refresh from sheet':'Sheet snapshot · Sep 14'}</button></div>
 <section className="poster-grid" aria-label="Watchlist titles">{rows.slice(0,limit).map(r=>{const cue=releaseCue(r,today);return <article className="title-card" key={r.id}><button className="poster-button" onClick={()=>{setSelected(r);setSaveError('')}} aria-label={'Details for '+r.title}>{r.poster?<img src={r.poster} alt={r.title+' poster'} loading="lazy"/>:<div className="poster-fallback"><Film size={32}/><span>{r.title}</span></div>}{cue.rank<2&&<span className={'release-badge '+(cue.rank===0?'upcoming':'recent')}>{cue.label} · {displayDate(cue.date)}</span>}<span className="poster-open">View details <ArrowUpRight size={16}/></span></button><div className="title-meta">{r.type||'Unconfirmed'}{r.year?' · '+r.year:''}</div><h2>{r.title}</h2><p className={'provider '+(r.availability==='available'?'available':'')}>{r.availability==='available'?r.providers[0]?.provider_name:['rent_buy_only','no_data'].includes(r.availability)?'No Steam Currently':'Needs clarification'}{new Set(r.providers.map(p=>p.provider_name)).size>1&&<span> +{new Set(r.providers.map(p=>p.provider_name)).size-1}</span>}</p>{offlineSources(r).length>0&&<span className="offline-hint" title={`Check ${offlineSources(r).join(" or ")} for an iPad download. Availability varies by title and season.`} aria-label={`Possible iPad download in ${offlineSources(r).join(" or ")}; check in app`}><Download size={13} aria-hidden="true"/> Check in app</span>}</article>})}</section>{!rows.length&&<div className="empty"><Search size={28}/><h2>No titles found</h2><p>Try another title or clear a filter.</p><button className="secondary" onClick={()=>{setQuery('');setType('all');setService('all');setAvailability('all');setTab('all')}}>Clear filters</button></div>}
 {rows.length>limit&&<div className="load-more"><button className="secondary" onClick={()=>setLimit(x=>x+30)}>Show more titles</button><span>{Math.min(limit,rows.length)} of {rows.length}</span></div>}
 <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><SheetContent className="detail-panel">{selected&&<><div className="detail-top">{selected.poster&&<img src={selected.poster} alt=""/>}<div><p className="title-meta">{selected.type||'Unconfirmed'}{selected.year?' · '+selected.year:''}</p><SheetTitle className="detail-title">{selected.title}</SheetTitle><SheetDescription>{selected.genres.join(' · ')||'From your watchlist'}</SheetDescription></div></div>{selected.overview&&<p className="synopsis">{selected.overview}</p>}<section><h3>Where to watch</h3>{selected.providers.length?<><ul className="provider-list">{selected.providers.map(p=><li key={p.provider_id+'-'+p.access_type}><span>{p.provider_name}</span><span>{({flatrate:'Included',free:'Free',ads:'Free with Ads'} as Record<string,string>)[p.access_type]}</span></li>)}</ul>{selected.sourceUrl&&<a className="watch-link" href={selected.sourceUrl} target="_blank" rel="noreferrer">See watching options <ArrowUpRight size={16}/></a>}</>:<p className="quiet">{['rent_buy_only','no_data'].includes(selected.availability)?'No Steam Currently':'This title needs clarification before checking availability.'}</p>}<p className="fine-print">{selected.checkedAt?'US availability checked '+new Date(selected.checkedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'Availability has not been checked.'}{selected.type==='Series'?' Availability may vary by season.':''}</p>{offlineSources(selected).length>0&&<p className="offline-detail"><Download size={16} aria-hidden="true"/><span><strong>iPad download option</strong> · Check in {offlineSources(selected).join(' or ')}. Downloads vary by title, plan, and season.</span></p>}</section><section><h3>Your watch status</h3><Select value={selected.status} onValueChange={v=>void changeStatus(v)} disabled={saving||!connected}><SelectTrigger className="status-select"><SelectValue/></SelectTrigger><SelectContent>{['Want to Watch','Watching','Watched','Dropped'].map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select>{!connected&&<p className="fine-print">Connect Google Sheets to save changes.</p>}</section>{selected.notes&&<section><h3>Your notes</h3><p className="quiet notes">{selected.notes}</p></section>}{saveError&&<p role="alert" className="form-error">{saveError}</p>}</>}</SheetContent></Sheet>
 <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent className="add-dialog"><DialogTitle>Add to your watchlist</DialogTitle><DialogDescription>Search a title to check included, free, and ad-supported US services before adding it.</DialogDescription><form onSubmit={addTitle}><label>Title<div className="title-search"><input required autoFocus maxLength={250} value={title} onChange={e=>{setTitle(e.target.value);setSearchResults([])}} placeholder="Movie or show name"/><button className="secondary" type="button" onClick={()=>void searchTitles()} disabled={searching}>{searching?'Searching…':'Check services'}</button></div></label>{searchError&&<p role="alert" className="form-error">{searchError}</p>}{searchResults.length>0&&<div className="search-results" aria-label="Search results">{searchResults.map(result=><button type="button" className="search-result" key={`${result.type}-${result.tmdbId}`} onClick={()=>chooseResult(result)}>{result.poster?<img src={result.poster} alt=""/>:<Film size={18}/>}<span><strong>{result.title}</strong><small>{result.type}{result.year?` · ${result.year}`:''} · {result.available?result.providers.map(p=>p.provider_name).filter((value,index,all)=>all.indexOf(value)===index).join(', '):'No Stream Currently'}</small></span></button>)}</div>}<label>Network / service <span>(optional)</span><input maxLength={150} value={hint} onChange={e=>setHint(e.target.value)} placeholder="e.g. Netflix"/></label>{!connected&&<p className="fine-print">Connect Google Sheets before saving. Your entry will stay here.</p>}{saveError&&<p role="alert" className="form-error">{saveError}</p>}<div className="form-actions"><button type="button" className="secondary" onClick={()=>setAddOpen(false)}>Cancel</button>{connected?<button className="primary" disabled={saving}>{saving?'Saving…':'Add title'}</button>:<button className="primary" type="button" onClick={()=>setConnectionOpen(true)}>Connect sheet</button>}</div></form></DialogContent></Dialog>
 <Dialog open={connectionOpen} onOpenChange={setConnectionOpen}><DialogContent><DialogTitle>Connect your Google Sheet</DialogTitle><DialogDescription>Your list is ready to browse. One connection enables live changes in both directions.</DialogDescription><ol className="setup-steps"><li>Open Show List and choose <strong>Extensions → Apps Script</strong>.</li><li>Paste the connection script provided in this task.</li><li>Choose <strong>Deploy → New deployment → Web app</strong>. Run as yourself, allow access to Anyone, and authorize it in Google.</li><li>Send the deployment URL in this task. The connection uses a private key and only supports this watchlist.</li></ol><a className="primary" href="https://docs.google.com/spreadsheets/d/1QHdc7GR5HxY3rJuOvsYe0Bf7b5TZcxXzeW8YuXub5qU/edit" target="_blank" rel="noreferrer">Open Show List <ArrowUpRight size={16}/></a></DialogContent></Dialog>
 <footer><span>This product uses the TMDB API but is not endorsed or certified by TMDB.</span><span>Streaming data: JustWatch via TMDB <a href="https://www.themoviedb.org" target="_blank" rel="noreferrer">About the data <ArrowUpRight size={13}/></a></span></footer></main></>
}
